// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwnU27W10QMhI2xFkURcA72BgMcIABbd4',
    appId: '1:708834972189:web:26788b1bf91143fa41ecf4',
    messagingSenderId: '708834972189',
    projectId: 'workoutlogger-712b0',
    authDomain: 'workoutlogger-712b0.firebaseapp.com',
    storageBucket: 'workoutlogger-712b0.firebasestorage.app',
    measurementId: 'G-Q30HW4VHMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWcKl29kphPfjkI9eN-ud6Ukto71CeznE',
    appId: '1:708834972189:android:ae813ebf837bdf7941ecf4',
    messagingSenderId: '708834972189',
    projectId: 'workoutlogger-712b0',
    storageBucket: 'workoutlogger-712b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaN6W8hSpx-JOG6A6eSMLXrWqmn4gVOOU',
    appId: '1:708834972189:ios:c389c1f2b364c73d41ecf4',
    messagingSenderId: '708834972189',
    projectId: 'workoutlogger-712b0',
    storageBucket: 'workoutlogger-712b0.firebasestorage.app',
    iosBundleId: 'com.example.workoutLoggerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaN6W8hSpx-JOG6A6eSMLXrWqmn4gVOOU',
    appId: '1:708834972189:ios:c389c1f2b364c73d41ecf4',
    messagingSenderId: '708834972189',
    projectId: 'workoutlogger-712b0',
    storageBucket: 'workoutlogger-712b0.firebasestorage.app',
    iosBundleId: 'com.example.workoutLoggerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwnU27W10QMhI2xFkURcA72BgMcIABbd4',
    appId: '1:708834972189:web:b55157fb37f0a5d541ecf4',
    messagingSenderId: '708834972189',
    projectId: 'workoutlogger-712b0',
    authDomain: 'workoutlogger-712b0.firebaseapp.com',
    storageBucket: 'workoutlogger-712b0.firebasestorage.app',
    measurementId: 'G-EPJB0JBXR6',
  );

}